USE [master]
GO

/****** Object:  Database [Daisy]    Script Date: 10/21/2015 22:06:41 ******/
CREATE DATABASE [Daisy] ON  PRIMARY 
( NAME = N'Daisy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Daisy.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Daisy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Daisy_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Daisy] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Daisy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Daisy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Daisy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Daisy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Daisy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Daisy] SET ARITHABORT OFF 
GO

ALTER DATABASE [Daisy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Daisy] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Daisy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Daisy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Daisy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Daisy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Daisy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Daisy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Daisy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Daisy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Daisy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Daisy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Daisy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Daisy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Daisy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Daisy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Daisy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Daisy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Daisy] SET  READ_WRITE 
GO

ALTER DATABASE [Daisy] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Daisy] SET  MULTI_USER 
GO

ALTER DATABASE [Daisy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Daisy] SET DB_CHAINING OFF 
GO


